// Generated by CoffeeScript 1.3.1
var height, output, page, url, width;

page = require('webpage').create();

url = phantom.args[0];

width = phantom.args[1];

height = phantom.args[2];

output = phantom.args[3];

page.viewportSize = {
  width: width,
  height: height
};

page.open(url, function() {
  page.render(output);
  return phantom.exit();
});
